#SingleInstance force
#NoEnv
#Warn

SendMode Input

Suspend, On
^#!m::Suspend

~BS::
~Del::
~Home::
~End::
~PgUp::
~PgDn::
~Left::
~Right::
~Enter::
~LButton::
~RButton::
  Hotstring("Reset")

SwapInChar(char, backspaceQty) {
  Send, {bs %backspaceQty%}
  SendRaw, %char%
}

Hotstring(":*?B0COXZ:varepsilon", Func("SwapInChar").Bind("𝜀", 7))
Hotstring(":*?B0COXZ:vartheta", Func("SwapInChar").Bind("𝜗", 7))
Hotstring(":*?B0COXZ:root(3)", Func("SwapInChar").Bind("∛", 5))
Hotstring(":*?B0COXZ:root(4)", Func("SwapInChar").Bind("∜", 5))
Hotstring(":*?B0COXZ:diamond", Func("SwapInChar").Bind("⋄", 6))
Hotstring(":*?B0COXZ: cancel", Func("SwapInChar").Bind("̸", 6))
Hotstring(":*?B0COXZ:epsilon", Func("SwapInChar").Bind("𝜖", 4))
Hotstring(":*?B0COXZ:upsilon", Func("SwapInChar").Bind("𝜐", 4))
Hotstring(":*?B0COXZ:iiiint", Func("SwapInChar").Bind("⨌", 4))
Hotstring(":*?B0COXZ:oiiint", Func("SwapInChar").Bind("∰", 4))
Hotstring(":*?B0COXZ:square", Func("SwapInChar").Bind("□", 5))
Hotstring(":*?B0COXZ:Delta=", Func("SwapInChar").Bind("≜", 1))
Hotstring(":*?B0COXZ:(1/10)", Func("SwapInChar").Bind("⅒", 5))
Hotstring(":*?B0COXZ:arcsin", Func("SwapInChar").Bind("arcsin", 5))
Hotstring(":*?B0COXZ:arccos", Func("SwapInChar").Bind("arccos", 5))
Hotstring(":*?B0COXZ:arctan", Func("SwapInChar").Bind("arctan", 5))
Hotstring(":*?B0COXZ:Lambda", Func("SwapInChar").Bind("𝛬", 5))
Hotstring(":*?B0COXZ:lambda", Func("SwapInChar").Bind("𝜆", 5))
Hotstring(":*?B0COXZ:varphi", Func("SwapInChar").Bind("𝜑", 5))
Hotstring(":*?B0COXZ:iiint", Func("SwapInChar").Bind("∭", 3))
Hotstring(":*?B0COXZ:oiint", Func("SwapInChar").Bind("∯", 3))
Hotstring(":*?B0COXZ:aleph", Func("SwapInChar").Bind("ℵ", 4))
Hotstring(":*?B0COXZ:cdots", Func("SwapInChar").Bind("⋯", 4))
Hotstring(":*?B0COXZ:vdots", Func("SwapInChar").Bind("⋮", 4))
Hotstring(":*?B0COXZ:ddots", Func("SwapInChar").Bind("⋱", 4))
Hotstring(":*?B0COXZ:frown", Func("SwapInChar").Bind("⏜", 4))
Hotstring(":*?B0COXZ:(1/4)", Func("SwapInChar").Bind("¼", 4))
Hotstring(":*?B0COXZ:(1/2)", Func("SwapInChar").Bind("½", 4))
Hotstring(":*?B0COXZ:(3/4)", Func("SwapInChar").Bind("¾", 4))
Hotstring(":*?B0COXZ:(1/7)", Func("SwapInChar").Bind("⅐", 4))
Hotstring(":*?B0COXZ:(1/9)", Func("SwapInChar").Bind("⅑", 4))
Hotstring(":*?B0COXZ:(1/3)", Func("SwapInChar").Bind("⅓", 4))
Hotstring(":*?B0COXZ:(2/3)", Func("SwapInChar").Bind("⅔", 4))
Hotstring(":*?B0COXZ:(1/5)", Func("SwapInChar").Bind("⅕", 4))
Hotstring(":*?B0COXZ:(2/5)", Func("SwapInChar").Bind("⅖", 4))
Hotstring(":*?B0COXZ:(3/5)", Func("SwapInChar").Bind("⅗", 4))
Hotstring(":*?B0COXZ:(4/5)", Func("SwapInChar").Bind("⅘", 4))
Hotstring(":*?B0COXZ:(1/6)", Func("SwapInChar").Bind("⅙", 4))
Hotstring(":*?B0COXZ:(5/6)", Func("SwapInChar").Bind("⅚", 4))
Hotstring(":*?B0COXZ:(1/8)", Func("SwapInChar").Bind("⅛", 4))
Hotstring(":*?B0COXZ:(3/8)", Func("SwapInChar").Bind("⅜", 4))
Hotstring(":*?B0COXZ:(5/8)", Func("SwapInChar").Bind("⅝", 4))
Hotstring(":*?B0COXZ:(7/8)", Func("SwapInChar").Bind("⅞", 4))
Hotstring(":*?B0COXZ: ddot", Func("SwapInChar").Bind("̈", 4))
Hotstring(":*?B0COXZ:Gamma", Func("SwapInChar").Bind("𝛤", 4))
Hotstring(":*?B0COX:Delta", Func("SwapInChar").Bind("𝛥", 2))
Hotstring(":*?B0COXZ:Theta", Func("SwapInChar").Bind("𝛩", 4))
Hotstring(":*?B0COXZ:Sigma", Func("SwapInChar").Bind("𝛴", 4))
Hotstring(":*?B0COXZ:Omega", Func("SwapInChar").Bind("𝛺", 4))
Hotstring(":*?B0COXZ:alpha", Func("SwapInChar").Bind("𝛼", 4))
Hotstring(":*?B0COXZ:gamma", Func("SwapInChar").Bind("𝛾", 4))
Hotstring(":*?B0COXZ:delta", Func("SwapInChar").Bind("𝛿", 2))
Hotstring(":*?B0COXZ:theta", Func("SwapInChar").Bind("𝜃", 4))
Hotstring(":*?B0COXZ:kappa", Func("SwapInChar").Bind("𝜅", 4))
Hotstring(":*?B0COXZ:sigma", Func("SwapInChar").Bind("𝜎", 4))
Hotstring(":*?B0COXZ:omega", Func("SwapInChar").Bind("𝜔", 4))
Hotstring(":*?B0COXZ:|><|", Func("SwapInChar").Bind("⋈", 1))
Hotstring(":*?B0COXZ:prod", Func("SwapInChar").Bind("∏", 3))
Hotstring(":*?B0COXZ:sqrt", Func("SwapInChar").Bind("√", 3))
Hotstring(":*?B0COXZ:iint", Func("SwapInChar").Bind("∬", 2))
Hotstring(":*?B0COXZ:oint", Func("SwapInChar").Bind("∮", 2))
Hotstring(":*?B0COXZ:grad", Func("SwapInChar").Bind("∇", 3))
Hotstring(":*?B0COXZ:''''", Func("SwapInChar").Bind("⁗", 1))
Hotstring(":*?B0COXZ:quad", Func("SwapInChar").Bind(" ", 3))
Hotstring(":*?B0COXZ:prop", Func("SwapInChar").Bind("∝", 3))
Hotstring(":*?B0COXZ:sube", Func("SwapInChar").Bind("⊆", 1))
Hotstring(":*?B0COXZ:supe", Func("SwapInChar").Bind("⊇", 1))
Hotstring(":*?B0COXZ:lArr", Func("SwapInChar").Bind("⇐", 3))
Hotstring(":*?B0COXZ:uarr", Func("SwapInChar").Bind("↑", 3))
Hotstring(":*?B0COXZ:darr", Func("SwapInChar").Bind("↓", 3))
Hotstring(":*?B0COXZ:>->>", Func("SwapInChar").Bind("⤖", 1))
Hotstring(":*?B0COXZ: hat", Func("SwapInChar").Bind("̂", 3))
Hotstring(":*?B0COXZ: bar", Func("SwapInChar").Bind("̅", 3))
Hotstring(":*?B0COXZ: vec", Func("SwapInChar").Bind("⃗", 3))
Hotstring(":*?B0COXZ: dot", Func("SwapInChar").Bind("̇", 3))
Hotstring(":*?B0COXZ:sinh", Func("SwapInChar").Bind("sinh", 3))
Hotstring(":*?B0COXZ:cosh", Func("SwapInChar").Bind("cosh", 3))
Hotstring(":*?B0COXZ:tanh", Func("SwapInChar").Bind("tanh", 3))
Hotstring(":*?B0COXZ:sech", Func("SwapInChar").Bind("sech", 3))
Hotstring(":*?B0COXZ:csch", Func("SwapInChar").Bind("csch", 3))
Hotstring(":*?B0COXZ:coth", Func("SwapInChar").Bind("coth", 3))
Hotstring(":*?B0COXZ:beta", Func("SwapInChar").Bind("𝛽", 3))
Hotstring(":*?B0COXZ:zeta", Func("SwapInChar").Bind("𝜁", 3))
Hotstring(":*?B0COXZ:iota", Func("SwapInChar").Bind("𝜄", 3))
Hotstring(":*?B0COXZ:***", Func("SwapInChar").Bind("⋆", 1))
Hotstring(":*?B0COX:|><", Func("SwapInChar").Bind("⋉", 2))
Hotstring(":*?B0COXZ:><|", Func("SwapInChar").Bind("⋊", 2))
Hotstring(":*?B0COXZ:sum", Func("SwapInChar").Bind("∑", 2))
Hotstring(":*?B0COXZ:^^^", Func("SwapInChar").Bind("⋀", 1))
Hotstring(":*?B0COXZ:vvv", Func("SwapInChar").Bind("⋁", 1))
Hotstring(":*?B0COXZ:nnn", Func("SwapInChar").Bind("⋂", 1))
Hotstring(":*?B0COXZ:uuu", Func("SwapInChar").Bind("⋃", 1))
Hotstring(":*?B0COXZ:int", Func("SwapInChar").Bind("∫", 1))
Hotstring(":*?B0COX:del", Func("SwapInChar").Bind("∂", 2))
Hotstring(":*?B0COX:Del", Func("SwapInChar").Bind("∆", 2))
Hotstring(":*?B0COXZ:...", Func("SwapInChar").Bind("…", 2))
Hotstring(":*?B0COX:'''", Func("SwapInChar").Bind("‴", 1))
Hotstring(":*?B0COXZ:/_\", Func("SwapInChar").Bind("△", 1))
Hotstring(":*?B0COXZ:-<=", Func("SwapInChar").Bind("≼", 1))
Hotstring(":*?B0COXZ:>-=", Func("SwapInChar").Bind("≽", 1))
Hotstring(":*?B0COXZ:!in", Func("SwapInChar").Bind("∉", 2))
Hotstring(":*?B0COX:sub", Func("SwapInChar").Bind("⊂", 2))
Hotstring(":*?B0COX:sup", Func("SwapInChar").Bind("⊃", 2))
Hotstring(":*?B0COXZ:and", Func("SwapInChar").Bind("and", 2))
Hotstring(":*?B0COXZ:not", Func("SwapInChar").Bind("¬", 2))
Hotstring(":*?B0COXZ:_|_", Func("SwapInChar").Bind("⊥", 1))
Hotstring(":*?B0COXZ:|--", Func("SwapInChar").Bind("⊢", 2))
Hotstring(":*?B0COXZ:|==", Func("SwapInChar").Bind("⊨", 2))
Hotstring(":*?B0COXZ:<=>", Func("SwapInChar").Bind("⇔", 1))
Hotstring(":*?B0COXZ:-->", Func("SwapInChar").Bind("⟶", 2))
Hotstring(":*?B0COX:>->", Func("SwapInChar").Bind("↣", 1))
Hotstring(":*?B0COXZ:->>", Func("SwapInChar").Bind("↠", 1))
Hotstring(":*?B0COXZ:|->", Func("SwapInChar").Bind("↦", 2))
Hotstring(":*?B0COXZ:<--", Func("SwapInChar").Bind("⟵", 1))
Hotstring(":*?B0COXZ:<->", Func("SwapInChar").Bind("↔", 1))
Hotstring(":*?B0COXZ: ul", Func("SwapInChar").Bind("̲", 2))
Hotstring(":*?B0COX:sin", Func("SwapInChar").Bind("sin", 2))
Hotstring(":*?B0COX:cos", Func("SwapInChar").Bind("cos", 2))
Hotstring(":*?B0COX:tan", Func("SwapInChar").Bind("tan", 2))
Hotstring(":*?B0COX:sec", Func("SwapInChar").Bind("sec", 2))
Hotstring(":*?B0COX:csc", Func("SwapInChar").Bind("csc", 2))
Hotstring(":*?B0COX:cot", Func("SwapInChar").Bind("cot", 2))
Hotstring(":*?B0COXZ:exp", Func("SwapInChar").Bind("exp", 2))
Hotstring(":*?B0COXZ:log", Func("SwapInChar").Bind("log", 2))
Hotstring(":*?B0COXZ:mod", Func("SwapInChar").Bind("mod", 2))
Hotstring(":*?B0COXZ:lim", Func("SwapInChar").Bind("lim", 2))
Hotstring(":*?B0COXZ:Phi", Func("SwapInChar").Bind("𝛷", 2))
Hotstring(":*?B0COXZ:Psi", Func("SwapInChar").Bind("𝛹", 2))
Hotstring(":*?B0COXZ:eta", Func("SwapInChar").Bind("𝜂", 2))
Hotstring(":*?B0COXZ:rho", Func("SwapInChar").Bind("𝜌", 2))
Hotstring(":*?B0COXZ:tau", Func("SwapInChar").Bind("𝜏", 2))
Hotstring(":*?B0COXZ:phi", Func("SwapInChar").Bind("𝜙", 2))
Hotstring(":*?B0COXZ:chi", Func("SwapInChar").Bind("𝜒", 2))
Hotstring(":*?B0COX:psi", Func("SwapInChar").Bind("𝜓", 2))
Hotstring(":*?B0COX:**", Func("SwapInChar").Bind("∗", 1))
Hotstring(":*?B0COXZ:xx", Func("SwapInChar").Bind("×", 1))
Hotstring(":*?B0COXZ:-:", Func("SwapInChar").Bind("÷", 1))
Hotstring(":*?B0COXZ:o+", Func("SwapInChar").Bind("⊕", 1))
Hotstring(":*?B0COXZ:ox", Func("SwapInChar").Bind("⊗", 1))
Hotstring(":*?B0COXZ:o.", Func("SwapInChar").Bind("⊙", 1))
Hotstring(":*?B0COX:^^", Func("SwapInChar").Bind("∧", 1))
Hotstring(":*?B0COX:vv", Func("SwapInChar").Bind("∨", 1))
Hotstring(":*?B0COX:nn", Func("SwapInChar").Bind("∩", 1))
Hotstring(":*?B0COX:uu", Func("SwapInChar").Bind("∪", 1))
Hotstring(":*?B0COXZ:+-", Func("SwapInChar").Bind("±", 1))
Hotstring(":*?B0COXZ:-+", Func("SwapInChar").Bind("∓", 1))
Hotstring(":*?B0COXZ:O/", Func("SwapInChar").Bind("∅", 1))
Hotstring(":*?B0COX:oo", Func("SwapInChar").Bind("∞", 1))
Hotstring(":*?B0COXZ::.", Func("SwapInChar").Bind("∴", 1))
Hotstring(":*?B0COXZ::'", Func("SwapInChar").Bind("∵", 1))
Hotstring(":*?B0COX:''", Func("SwapInChar").Bind("″", 1))
Hotstring(":*?B0COXZ:  ", Func("SwapInChar").Bind(" ", 1))
Hotstring(":*?B0COX:/_", Func("SwapInChar").Bind("∠", 1))
Hotstring(":*?B0COXZ:CC", Func("SwapInChar").Bind("ℂ", 1))
Hotstring(":*?B0COXZ:NN", Func("SwapInChar").Bind("ℕ", 1))
Hotstring(":*?B0COXZ:QQ", Func("SwapInChar").Bind("ℚ", 1))
Hotstring(":*?B0COXZ:RR", Func("SwapInChar").Bind("ℝ", 1))
Hotstring(":*?B0COXZ:ZZ", Func("SwapInChar").Bind("ℤ", 1))
Hotstring(":*?B0COXZ:AA", Func("SwapInChar").Bind("∀", 1))
Hotstring(":*?B0COXZ:EE", Func("SwapInChar").Bind("∃", 1))
Hotstring(":*?B0COXZ::=", Func("SwapInChar").Bind("≔", 1))
Hotstring(":*?B0COXZ:!=", Func("SwapInChar").Bind("≠", 1))
Hotstring(":*?B0COXZ:?=", Func("SwapInChar").Bind("≟", 1))
Hotstring(":*?B0COXZ:-=", Func("SwapInChar").Bind("≡", 1))
Hotstring(":*?B0COXZ:~=", Func("SwapInChar").Bind("≅", 1))
Hotstring(":*?B0COXZ:~~", Func("SwapInChar").Bind("≈", 1))
Hotstring(":*?B0COXZ:<<", Func("SwapInChar").Bind("≪", 1))
Hotstring(":*?B0COXZ:>>", Func("SwapInChar").Bind("≫", 1))
Hotstring(":*?B0COX:<=", Func("SwapInChar").Bind("≤", 1))
Hotstring(":*?B0COXZ:>=", Func("SwapInChar").Bind("≥", 1))
Hotstring(":*?B0COX:-<", Func("SwapInChar").Bind("≺", 1))
Hotstring(":*?B0COX:>-", Func("SwapInChar").Bind("≻", 1))
Hotstring(":*?B0COX:in", Func("SwapInChar").Bind("∈", 1))
Hotstring(":*?B0COXZ:or", Func("SwapInChar").Bind("or", 1))
Hotstring(":*?B0COXZ:if", Func("SwapInChar").Bind("if", 1))
Hotstring(":*?B0COXZ:TT", Func("SwapInChar").Bind("⊤", 1))
Hotstring(":*?B0COXZ:|_", Func("SwapInChar").Bind("⌊", 1))
Hotstring(":*?B0COX:_|", Func("SwapInChar").Bind("⌋", 1))
Hotstring(":*?B0COXZ:|~", Func("SwapInChar").Bind("⌈", 1))
Hotstring(":*?B0COXZ:~|", Func("SwapInChar").Bind("⌉", 1))
Hotstring(":*?B0COXZ:(:", Func("SwapInChar").Bind("⟨", 1))
Hotstring(":*?B0COXZ::)", Func("SwapInChar").Bind("⟩", 1))
Hotstring(":*?B0COXZ:=>", Func("SwapInChar").Bind("⇒", 1))
Hotstring(":*?B0COX:->", Func("SwapInChar").Bind("→", 1))
Hotstring(":*?B0COX:<-", Func("SwapInChar").Bind("←", 1))
Hotstring(":*?B0COXZ:ln", Func("SwapInChar").Bind("ln", 1))
Hotstring(":*?B0COXZ:Xi", Func("SwapInChar").Bind("𝛯", 1))
Hotstring(":*?B0COXZ:Pi", Func("SwapInChar").Bind("𝛱", 1))
Hotstring(":*?B0COXZ:mu", Func("SwapInChar").Bind("𝜇", 1))
Hotstring(":*?B0COXZ:nu", Func("SwapInChar").Bind("𝜈", 1))
Hotstring(":*?B0COXZ:xi", Func("SwapInChar").Bind("𝜉", 1))
Hotstring(":*?B0COXZ:pi", Func("SwapInChar").Bind("𝜋", 1))
Hotstring(":*?B0COX:+", Func("SwapInChar").Bind("+", 0))
Hotstring(":*?B0COX:-", Func("SwapInChar").Bind("−", 0))
Hotstring(":*?B0COX:*", Func("SwapInChar").Bind("⋅", 0))
Hotstring(":*?B0COX:/", Func("SwapInChar").Bind("∕", 0))
Hotstring(":*?B0COXZ:\", Func("SwapInChar").Bind("∖", 0))
Hotstring(":*?B0COX::", Func("SwapInChar").Bind("∶", 0))
Hotstring(":*?B0COX:!", Func("SwapInChar").Bind("!", 0))
Hotstring(":*?B0COX:'", Func("SwapInChar").Bind("′", 0))
Hotstring(":*?B0COX: ", Func("SwapInChar").Bind(" ", 0))
Hotstring(":*?B0COXZ:@", Func("SwapInChar").Bind("∘", 0))
Hotstring(":*?B0COX:=", Func("SwapInChar").Bind("=", 0))
Hotstring(":*?B0COX:<", Func("SwapInChar").Bind("<", 0))
Hotstring(":*?B0COX:>", Func("SwapInChar").Bind(">", 0))
Hotstring(":*?B0COX:(", Func("SwapInChar").Bind("(", 0))
Hotstring(":*?B0COXZ:)", Func("SwapInChar").Bind(")", 0))
Hotstring(":*?B0COXZ:[", Func("SwapInChar").Bind("[", 0))
Hotstring(":*?B0COXZ:]", Func("SwapInChar").Bind("]", 0))
Hotstring(":*?B0COXZ:{", Func("SwapInChar").Bind("{", 0))
Hotstring(":*?B0COXZ:}", Func("SwapInChar").Bind("}", 0))
Hotstring(":*?B0COX:|", Func("SwapInChar").Bind("|", 0))
Hotstring(":*?B0COX:a", Func("SwapInChar").Bind("𝑎", 0))
Hotstring(":*?B0COX:b", Func("SwapInChar").Bind("𝑏", 0))
Hotstring(":*?B0COX:c", Func("SwapInChar").Bind("𝑐", 0))
Hotstring(":*?B0COX:d", Func("SwapInChar").Bind("𝑑", 0))
Hotstring(":*?B0COX:e", Func("SwapInChar").Bind("𝑒", 0))
Hotstring(":*?B0COX:f", Func("SwapInChar").Bind("𝑓", 0))
Hotstring(":*?B0COX:g", Func("SwapInChar").Bind("𝑔", 0))
Hotstring(":*?B0COX:h", Func("SwapInChar").Bind("ℎ", 0))
Hotstring(":*?B0COX:i", Func("SwapInChar").Bind("𝑖", 0))
Hotstring(":*?B0COXZ:j", Func("SwapInChar").Bind("𝑗", 0))
Hotstring(":*?B0COX:k", Func("SwapInChar").Bind("𝑘", 0))
Hotstring(":*?B0COX:l", Func("SwapInChar").Bind("𝑙", 0))
Hotstring(":*?B0COX:m", Func("SwapInChar").Bind("𝑚", 0))
Hotstring(":*?B0COX:n", Func("SwapInChar").Bind("𝑛", 0))
Hotstring(":*?B0COX:o", Func("SwapInChar").Bind("𝑜", 0))
Hotstring(":*?B0COX:p", Func("SwapInChar").Bind("𝑝", 0))
Hotstring(":*?B0COX:q", Func("SwapInChar").Bind("𝑞", 0))
Hotstring(":*?B0COX:r", Func("SwapInChar").Bind("𝑟", 0))
Hotstring(":*?B0COX:s", Func("SwapInChar").Bind("𝑠", 0))
Hotstring(":*?B0COX:t", Func("SwapInChar").Bind("𝑡", 0))
Hotstring(":*?B0COX:u", Func("SwapInChar").Bind("𝑢", 0))
Hotstring(":*?B0COX:v", Func("SwapInChar").Bind("𝑣", 0))
Hotstring(":*?B0COX:w", Func("SwapInChar").Bind("𝑤", 0))
Hotstring(":*?B0COX:x", Func("SwapInChar").Bind("𝑥", 0))
Hotstring(":*?B0COXZ:y", Func("SwapInChar").Bind("𝑦", 0))
Hotstring(":*?B0COX:z", Func("SwapInChar").Bind("𝑧", 0))
Hotstring(":*?B0COX:A", Func("SwapInChar").Bind("𝐴", 0))
Hotstring(":*?B0COXZ:B", Func("SwapInChar").Bind("𝐵", 0))
Hotstring(":*?B0COX:C", Func("SwapInChar").Bind("𝐶", 0))
Hotstring(":*?B0COX:D", Func("SwapInChar").Bind("𝐷", 0))
Hotstring(":*?B0COX:E", Func("SwapInChar").Bind("𝐸", 0))
Hotstring(":*?B0COXZ:F", Func("SwapInChar").Bind("𝐹", 0))
Hotstring(":*?B0COX:G", Func("SwapInChar").Bind("𝐺", 0))
Hotstring(":*?B0COXZ:H", Func("SwapInChar").Bind("𝐻", 0))
Hotstring(":*?B0COXZ:I", Func("SwapInChar").Bind("𝐼", 0))
Hotstring(":*?B0COXZ:J", Func("SwapInChar").Bind("𝐽", 0))
Hotstring(":*?B0COXZ:K", Func("SwapInChar").Bind("𝐾", 0))
Hotstring(":*?B0COX:L", Func("SwapInChar").Bind("𝐿", 0))
Hotstring(":*?B0COXZ:M", Func("SwapInChar").Bind("𝑀", 0))
Hotstring(":*?B0COX:N", Func("SwapInChar").Bind("𝑁", 0))
Hotstring(":*?B0COX:O", Func("SwapInChar").Bind("𝑂", 0))
Hotstring(":*?B0COX:P", Func("SwapInChar").Bind("𝑃", 0))
Hotstring(":*?B0COX:Q", Func("SwapInChar").Bind("𝑄", 0))
Hotstring(":*?B0COX:R", Func("SwapInChar").Bind("𝑅", 0))
Hotstring(":*?B0COX:S", Func("SwapInChar").Bind("𝑆", 0))
Hotstring(":*?B0COX:T", Func("SwapInChar").Bind("𝑇", 0))
Hotstring(":*?B0COXZ:U", Func("SwapInChar").Bind("𝑈", 0))
Hotstring(":*?B0COXZ:V", Func("SwapInChar").Bind("𝑉", 0))
Hotstring(":*?B0COXZ:W", Func("SwapInChar").Bind("𝑊", 0))
Hotstring(":*?B0COX:X", Func("SwapInChar").Bind("𝑋", 0))
Hotstring(":*?B0COXZ:Y", Func("SwapInChar").Bind("𝑌", 0))
Hotstring(":*?B0COX:Z", Func("SwapInChar").Bind("𝑍", 0))
Hotstring(":*?B0COX:0", Func("SwapInChar").Bind("0", 0))
Hotstring(":*?B0COX:1", Func("SwapInChar").Bind("1", 0))
Hotstring(":*?B0COX:2", Func("SwapInChar").Bind("2", 0))
Hotstring(":*?B0COX:3", Func("SwapInChar").Bind("3", 0))
Hotstring(":*?B0COX:4", Func("SwapInChar").Bind("4", 0))
Hotstring(":*?B0COX:5", Func("SwapInChar").Bind("5", 0))
Hotstring(":*?B0COX:6", Func("SwapInChar").Bind("6", 0))
Hotstring(":*?B0COX:7", Func("SwapInChar").Bind("7", 0))
Hotstring(":*?B0COX:8", Func("SwapInChar").Bind("8", 0))
Hotstring(":*?B0COX:9", Func("SwapInChar").Bind("9", 0))
