module.exports = [
  { input: '+', output: '+' },
  { input: '-', output: '−' },
  { input: '*', output: '⋅' },
  { input: '**', output: '∗' },
  { input: '***', output: '⋆' },
  { input: '/', output: '∕' },
  { input: '\\', output: '∖' },
  { input: 'xx', output: '×' },
  { input: '-:', output: '÷' },
  { input: ':', output: '∶' },
  { input: '!', output: '!' },
  { input: '+-', output: '±' },
  { input: '-+', output: '∓' },

  { input: '|><', output: '⋉' },
  { input: '><|', output: '⋊' },
  { input: '|><|', output: '⋈' },
  { input: 'o+', output: '⊕' },
  { input: 'ox', output: '⊗' },
  { input: 'o.', output: '⊙' },

  { input: 'sqrt', output: '√' },
  { input: 'root(3)', output: '∛' },
  { input: 'root(4)', output: '∜' },

  { input: 'sum', output: '∑' },
  { input: 'prod', output: '∏' },
  { input: 'int', output: '∫' },
  { input: 'iint', output: '∬' },
  { input: 'iiint', output: '∭' },
  { input: 'iiiint', output: '⨌' },
  { input: 'oint', output: '∮' },
  { input: 'oiint', output: '∯' },
  { input: 'oiiint', output: '∰' },

  { input: ':.', output: '∴' },
  { input: ":'", output: '∵' },
  { input: '...', output: '…' },
  { input: 'cdots', output: '⋯' },
  { input: 'vdots', output: '⋮' },
  { input: 'ddots', output: '⋱' },

  { input: "'", output: '′' },
  { input: "''", output: '″' },
  { input: "'''", output: '‴' },
  { input: "''''", output: '⁗' },

  { input: ' ', output: '\u2006' },
  { input: '  ', output: '\u2004' },
  { input: 'quad', output: '\u2003' },

  { input: '|_', output: '⌊' },
  { input: '_|', output: '⌋' },
  { input: '|~', output: '⌈' },
  { input: '~|', output: '⌉' },
  { input: '(', output: '(' },
  { input: ')', output: ')' },
  { input: '[', output: '[' },
  { input: ']', output: ']' },
  { input: '{', output: '{' },
  { input: '}', output: '}' },
  { input: '(:', output: '⟨' },
  { input: ':)', output: '⟩' },
  { input: '|', output: '|' },
  { input: '||', output: '‖' },

  { input: '(1/4)', output: '¼' },
  { input: '(1/2)', output: '½' },
  { input: '(3/4)', output: '¾' },
  { input: '(1/7)', output: '⅐' },
  { input: '(1/9)', output: '⅑' },
  { input: '(1/10)', output: '⅒' },
  { input: '(1/3)', output: '⅓' },
  { input: '(2/3)', output: '⅔' },
  { input: '(1/5)', output: '⅕' },
  { input: '(2/5)', output: '⅖' },
  { input: '(3/5)', output: '⅗' },
  { input: '(4/5)', output: '⅘' },
  { input: '(1/6)', output: '⅙' },
  { input: '(5/6)', output: '⅚' },
  { input: '(1/8)', output: '⅛' },
  { input: '(3/8)', output: '⅜' },
  { input: '(5/8)', output: '⅝' },
  { input: '(7/8)', output: '⅞' },

  { input: '/_', output: '∠' },
  { input: 'frown', output: '⌢' },
  { input: '/_\\', output: '△' },
  { input: 'diamond', output: '⋄' },
  { input: 'square', output: '□' },
  { input: '@', output: '∘' },

  { input: 'CC', output: 'ℂ' },
  { input: 'NN', output: 'ℕ' },
  { input: 'QQ', output: 'ℚ' },
  { input: 'RR', output: 'ℝ' },
  { input: 'ZZ', output: 'ℤ' },
  { input: 'AA', output: '∀' },
  { input: 'EE', output: '∃' },

  { input: '_|_', output: '⊥' },
  { input: 'TT', output: '⊤' },
  { input: '|-', output: '⊢' },
  { input: '|=', output: '⊨' },

  { input: '=', output: '=' },
  { input: ':=', output: '≔' },
  { input: '!=', output: '≠' },
  { input: '?=', output: '≟' },
  { input: 'Delta=', output: '≜' },
  { input: '-=', output: '≡' },
  { input: '~=', output: '≅' },
  { input: '~~', output: '≈' },
  { input: 'prop', output: '∝' },

  { input: '<', output: '<' },
  { input: '<=', output: '≤' },
  { input: '?<', output: '⩻' },
  { input: '!<', output: '≮' },
  { input: '!<=', output: '≰' },
  { input: '<<', output: '≪' },
  { input: '<<<', output: '⋘' },

  { input: '>', output: '>' },
  { input: '>=', output: '≥' },
  { input: '?>', output: '⩼' },
  { input: '!>', output: '≯' },
  { input: '!>=', output: '≱' },
  { input: '>>', output: '≫' },
  { input: '>>>', output: '⋙' },

  { input: '-<', output: '≺' },
  { input: '-<=', output: '≼' },
  { input: '>-', output: '≻' },
  { input: '>-=', output: '≽' },
  { input: 'in', output: '∈' },
  { input: '!in', output: '∉' },
  { input: 'sub', output: '⊂' },
  { input: 'sup', output: '⊃' },
  { input: 'sub=', output: '⊆' },
  { input: 'sup=', output: '⊇' },

  { input: '<=>', output: '⇔' },
  { input: '=>', output: '⇒' },
  { input: 'lArr', output: '⇐' },
  { input: 'uarr', output: '↑' },
  { input: 'darr', output: '↓' },
  { input: '->', output: '→' },
  { input: '-->', output: '⟶' },
  { input: '>->', output: '↣' },
  { input: '->>', output: '↠' },
  { input: '>->>', output: '⤖' },
  { input: '|->', output: '↦' },
  { input: '<-', output: '←' },
  { input: '<--', output: '⟵' },
  { input: '<->', output: '↔' },

  { input: '^^', output: '∧' },
  { input: '^^^', output: '⋀' },
  { input: 'vv', output: '∨' },
  { input: 'vvv', output: '⋁' },
  { input: 'nn', output: '∩' },
  { input: 'nnn', output: '⋂' },
  { input: 'uu', output: '∪' },
  { input: 'uuu', output: '⋃' },
  { input: 'not', output: '¬' },

  { input: 'del', output: '∂' },
  { input: 'Del', output: '∆' },
  { input: 'grad', output: '∇' },
  { input: 'O/', output: '∅' },
  { input: 'oo', output: '∞' },
  { input: 'aleph', output: 'ℵ' },

  { input: 'hat', output: '\u0302' },
  { input: 'bar', output: '\u0305' },
  { input: 'ul', output: '\u0332' },
  { input: 'vec', output: '\u20D7' },
  { input: 'dot', output: '\u0307' },
  { input: 'ddot', output: '\u0308' },
  { input: 'cancel', output: '\u0338' },
];
